project/myapp/urls.py
from rest_framework.routers import DefaultRouter
from .views import AutorViewSet, LibroViewSet
from django.urls import path, include
from django.contrib import admin
from myapp import views


router = DefaultRouter()
router.register(r'autores', AutorViewSet)
router.register(r'libros', LibroViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),

    # Página principal
    path('', views.PaginaPrincipalView.as_view(), name='index'),

    # Autores
    path('autores/', views.AutorListView.as_view(), name='lista_autores'),
    path('autores/<int:pk>/', views.AutorDetailView.as_view(), name='detalle_autor'),
    path('autores/nuevo/', views.AutorCreateView.as_view(), name='add_autor'),
    path('autores/<int:pk>/edit/', views.AutorUpdateView.as_view(), name='edit_autor'),
    path('autores/<int:pk>/delete/', views.AutorDeleteView.as_view(), name='delete_autor'),

    # Libros
    path('libros/', views.LibroListView.as_view(), name='lista_libros'),
    path('libros/<int:pk>/', views.LibroDetailView.as_view(), name='detalle_libro'),
    path('libros/nuevo/', views.LibroCreateView.as_view(), name='add_book'),
    path('libros/<int:pk>/edit/', views.LibroUpdateView.as_view(), name='edit_book'),
    path('libros/<int:pk>/delete/', views.LibroDeleteView.as_view(), name='delete_book'),

    # Autenticación
    path('accounts/login/', views.CustomLoginView.as_view(), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    #api
     path('api/', include(router.urls)),
]

project/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestion/', include('myapp.urls')),
     path('', include('myapp.urls')), 
]

project/myapp/models.py
from django.db import models

class Autor(models.Model):
    nombre= models.CharField(max_length=100)
    apellido= models.CharField(max_length=100)
    fecha_nacimiento= models.DateField()
    
    def __str__(self):
        return f"{self.nombre} {self.apellido}"
        
class Libro(models.Model):
    titulo = models.CharField(max_length=100)
    fecha_publi = models.DateField()
    genero = models.CharField(max_length=100)
    isbn = models.CharField(max_length=13,unique=True)
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.titulo

project/myapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from .models import Libro, Autor
from .serializers import AutorSerializer, LibroSerializer
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticatedOrReadOnly


class CustomLoginView(LoginView):
    template_name = 'registration/login.html'
    redirect_authenticated_user = True  # Redirige si ya está autenticado
    success_url = reverse_lazy('index')

class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Registro exitoso. Ahora puedes iniciar sesión ✅")
        return response

class PaginaPrincipalView(TemplateView):
    template_name = 'index.html'

class AutorListView(ListView):
    model = Autor
    template_name = 'lista_autores.html'

class AutorDetailView(DetailView):
    model = Autor
    template_name = 'detalle_autor.html'
    context_object_name = 'autor'

class LibroListView(ListView):
    model = Libro
    template_name = 'lista_libros.html'

class LibroDetailView(DetailView):
    model = Libro
    template_name = 'detalle_libro.html'
    context_object_name = 'libro'

class AutorCreateView(LoginRequiredMixin, CreateView):
    model = Autor
    template_name = 'add_autor.html'
    fields = ['nombre', 'apellido', 'fecha_nacimiento']
    success_url = reverse_lazy('lista_autores')

    def form_valid(self, form):
        messages.success(self.request, "Autor añadido correctamente ✅")
        return super().form_valid(form)

class LibroCreateView(LoginRequiredMixin, CreateView):
    model = Libro
    template_name = 'add_book.html'
    fields = ['titulo', 'fecha_publi', 'genero', 'isbn', 'autor']
    success_url = reverse_lazy('lista_libros')

    def form_valid(self, form):
        messages.success(self.request, "Libro añadido correctamente ✅")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Error al añadir el libro ❌")
        return self.render_to_response(self.get_context_data(form=form))

class AutorUpdateView(LoginRequiredMixin, UpdateView):
    model = Autor
    fields = ['nombre', 'apellido', 'fecha_nacimiento']
    template_name = 'edit_autor.html'
    success_url = reverse_lazy('lista_autores')

    def form_valid(self, form):
        messages.success(self.request, "Autor actualizado correctamente ✅")
        return super().form_valid(form)

class LibroUpdateView(LoginRequiredMixin, UpdateView):
    model = Libro
    template_name = 'edit_book.html'
    fields = ['titulo', 'fecha_publi', 'genero', 'isbn', 'autor']
    success_url = reverse_lazy('lista_libros')

    def form_valid(self, form):
        messages.success(self.request, "Libro actualizado correctamente ✅")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Error al actualizar el libro ❌")
        return self.render_to_response(self.get_context_data(form=form))

class AutorDeleteView(LoginRequiredMixin, DeleteView):
    model = Autor
    template_name = 'delete_autor.html'
    success_url = reverse_lazy('lista_autores')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "Autor eliminado correctamente ✅")
        return super().delete(request, *args, **kwargs)

class LibroDeleteView(LoginRequiredMixin, DeleteView):
    model = Libro
    template_name = 'delete_book.html'
    success_url = reverse_lazy('lista_libros')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "Libro eliminado correctamente ✅")
        return super().delete(request, *args, **kwargs)


class AutorViewSet(viewsets.ModelViewSet):
    queryset = Autor.objects.all()
    serializer_class = AutorSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]

class LibroViewSet(viewsets.ModelViewSet):
    queryset = Libro.objects.all()
    serializer_class = LibroSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]

project/templates/add_autor.html
{% extends 'layouts/base.html' %}

{% block title %}Añadir autor{% endblock %}

{% block content %}

    <h2 class="text-2xl font-bold mb-4">Añadir un Nuevo Autor</h2>
    
    <form method="post">
        {% csrf_token %}

        <label class="block text-gray-700 text-sm font-bold mb-2">Nombre:
        <input type="text" name="nombre" class="form-input border rounded px-2 py-1"></label>

        <label class="block text-gray-700 text-sm font-bold mb-2">Apellido:
        <input type="text" name="apellido" class="form-input border rounded px-2 py-1"></label>
        
        <label class="block text-gray-700 text-sm font-bold mb-2">Fecha de Nacimiento:
        <input type="date" name="fecha_nacimiento" class="form-input border rounded px-2 py-1"></label>

        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-lg mt-3">Guardar</button>
        <a href="{% url 'lista_autores' %}" class="ml-4 text-blue-500">Cancelar</a>
    </form>

{% endblock %}

project/templates/add_book.html
{% extends 'layouts/base.html' %}

{% block title %}Añadir Libro{% endblock %}

{% block content %}

    <h2 class="text-2xl font-bold mb-4">Añadir un Nuevo Libro</h2>
    
    <form method="post">
        {% csrf_token %}

        <label class="block text-gray-700 text-sm font-bold mb-2">Nombre:
        <input type="text" name="titulo" class="form-input border rounded px-2 py-1"></label>
        
        <label class="block text-gray-700 text-sm font-bold mb-2">Fecha de Lanzamiento:
        <input type="date" name="fecha_publi" class="form-input border rounded px-2 py-1"></label>

        <label class="block text-gray-700 text-sm font-bold mb-2">Genero:
        <input type="text" name="genero" class="form-input border rounded px-2 py-1"></label>

        <label class="block text-gray-700 text-sm font-bold mb-2">ISBN:
        <input type="number" name="isbn" class="form-input border rounded px-2 py-1"></label>

        <label class="block text-gray-700 text-sm font-bold mb-2">Autor:
        <select name="autor">
            <option value="">...</option>
            {% for autor in autores %}
            <option value="{{ autor.id }}" class="capitalize">{{ autor.nombre }} {{ autor.apellido }}</option>
            {% endfor %}
        </select></label>
        
        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-lg mt-3">Guardar</button>
        <a href="{% url 'lista_libros' %}" class="ml-4 text-blue-500">Cancelar</a>
    </form>
{% endblock %}

project/templates/delete_autor.html
{% extends 'layouts/base.html' %}

{% block title %}{{ autor.nombre }} {{ autor.apellido }}{% endblock %}

{% block content %}
<div class="max-w-4xl mx-auto  bg-white rounded-lg flex flex-col items-center">
  <h2>¿Estás seguro de que quieres eliminar a "{{ autor.nombre }}"?</h2>
  <form method="post">
    {% csrf_token %}
    <div class="mt-3 ">
      <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded inline-flex items-center justify-center">Eliminar</button>
    <a href="{% url 'lista_autores' %}" class="bg-gray-500 text-white px-4 py-2 rounded inline-flex items-center justify-center">CancelarZ</a>
    </div>
  </form>
</div>
{% endblock %}

project/templates/delete_book.html
{% extends 'layouts/base.html' %}

{% block title %}Eliminar{% endblock %}

{% block content %}
<div class="max-w-4xl mx-auto  bg-white rounded-lg flex flex-col items-center">
  <h2>¿Estás seguro de que quieres eliminar a "{{ libro.titulo }}"?</h2>
  <form method="post">
    {% csrf_token %}
    <div class="mt-3 ">
      <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded inline-flex items-center justify-center">Eliminar</button>
    <a href="{%  url 'detalle_libro' libro.id %}" class="bg-gray-500 text-white px-4 py-2 rounded inline-flex items-center justify-center">Cancelar</a>
    </div>
  </form>
</div>
{% endblock %}

project/templates/detalle_autor.html
{% extends 'layouts/base.html' %}

{% block title %}{{ object.nombre }} {{ object.apellido }}{% endblock %}

{% block content %}
<h1 class="text-2xl font-semibold mb-4 capitalize">{{ object.nombre }} {{ object.apellido }}</h1>
<p class="text-lg mb-4">Fecha de nacimiento: <span class="font-medium">{{ object.fecha_nacimiento }}</span></p>

<h2 class="text-xl font-bold mb-3">Libros de este autor:</h2>
<ul class="list-disc pl-6">
    {% for libro in object.libro_set.all %}
    <li class="mb-2">
        <a href="{% url 'detalle_libro' libro.id %}" class="text-blue-600 hover:underline">{{ libro.titulo }}</a>
    </li>
    {% empty %}
    <p class="text-gray-600">Este autor aún no tiene libros registrados.</p>
    {% endfor %}
</ul>
{% endblock %}

{% block actions %}
<div class="max-w-4xl mx-auto mt-8 bg-white rounded-lg flex flex-col items-center">
    <div class="flex gap-4 justify-center">
        <a href="{% url 'edit_autor' object.id %}" class="bg-green-600 p-3 text-white rounded-[10px] hover:bg-green-500">Editar Autor</a>
        <a href="{% url 'delete_autor' object.id  %}" class="bg-red-600 p-3 text-white rounded-[10px] hover:bg-red-500">Eliminar Autor</a>
    </div>
</div>

{% endblock%}

project/templates/detalle_libro.html
{% extends 'layouts/base.html' %}

{% block title %}{{ object.titulo }}{% endblock %}

{% block content %}
<h2 class="text-3xl font-bold mb-4 ">{{ object.titulo }}</h2>
<div class="text-lg text-gray-700 space-y-4 ">
    <p class="text-gray-900"><strong>Año de publicación:</strong> {{ object.fecha_publi }}</p>
    <p class="capitalize text-gray-900"><strong>Género:</strong> {{ object.genero }}</p>
    <p class="text-gray-900"><strong>ISBN:</strong> {{ object.isbn }}</p>
    <p>
        <strong class="text-gray-900">Autor:</strong> 
        <a href="{% url 'detalle_autor' object.autor.id %}" class="text-blue-600 hover:underline ">
            {{ object.autor.nombre }} {{ object.autor.apellido }}
        </a>
    </p>
</div>
{% endblock %}


{% block actions %}
<div class="max-w-4xl mx-auto mt-8 bg-white rounded-lg flex flex-col items-center">
    <div class="flex gap-4 justify-center">
        <a href="{% url 'edit_book' object.id %}" class="bg-green-600 p-3 text-white rounded-[10px] hover:bg-green-500">Editar Libro</a>
        <a href="{% url 'delete_book' object.id  %}" class="bg-red-600 p-3 text-white rounded-[10px] hover:bg-red-500">Eliminar Libro</a>
    </div>
</div>
{% endblock%}

project/templates/edit_autor.html
{% extends 'layouts/base.html' %}

{% block title %}Editar Autor{% endblock %}

{% block content %}

    <h2 class="text-2xl font-bold mb-4">Editar Autor</h2>
    
    <form method="post">
        {% csrf_token %}

        <label class="block text-gray-700 text-sm font-bold mb-2">Nombre:
        <input type="text" name="nombre" value="{{ autor.nombre }}" class="form-input border rounded px-2 py-1"></label>

        <label class="block text-gray-700 text-sm font-bold mb-2">Apellido:
        <input type="text" name="apellido" value="{{ autor.apellido }}" class="form-input border rounded px-2 py-1"></label>
        
        <label class="block text-gray-700 text-sm font-bold mb-2">Fecha de Nacimiento:
        <input type="date" name="fecha_nacimiento" value="{{ autor.fecha_nacimiento | date:'Y-m-d'  }}" class="form-input border rounded px-2 py-1"></label>

        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-lg mt-3">Guardar</button>
        <a href="{%url 'detalle_autor' autor.id %}" class="ml-4 text-blue-500">Cancelar</a>
    </form>

{% endblock %}

project/templates/edit_book.html
{% extends 'layouts/base.html' %}

{% block title %}Editar Libro{% endblock %}

{% block content %}

    <h2 class="text-2xl font-bold mb-4">Editar un Libro</h2>
    
    <form method="post">
        {% csrf_token %}

        <label class="block text-gray-700 text-sm font-bold mb-2">Nombre:
        <input type="text" name="titulo" value="{{libro.titulo}}" class="form-input border rounded px-2 py-1"></label>
        
        <label class="block text-gray-700 text-sm font-bold mb-2">Fecha de Lanzamiento:
        <input type="date" name="fecha_publi" value="{{ libro.fecha_publi | date:'Y-m-d'}}" class="form-input border rounded px-2 py-1"></label>

        <label class="block text-gray-700 text-sm font-bold mb-2">Genero:
        <input type="text" name="genero" value="{{libro.genero}}" class="form-input border rounded px-2 py-1"></label>

        <label class="block text-gray-700 text-sm font-bold mb-2">ISBN:
        <input type="number" name="isbn" value="{{libro.isbn}}" class="form-input border rounded px-2 py-1"></label>

        <label class="block text-gray-700 text-sm font-bold mb-2">Autor:
        <select name="autor" value="{{libro.autor}}">
            <option value="{{autor.id}}">...</option>
            {% for autor in autores %}
            <option value="{{ autor.id }}" class="capitalize">{{ autor.nombre }} {{ autor.apellido }}</option>
            {% endfor %}
        </select></label>
        
        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-lg mt-3">Guardar</button>
        <a href="{% url 'detalle_libro' libro.id %}" class="ml-4 text-blue-500">Cancelar</a>
    </form>
<br>
    {% if messages %}
        {% for message in messages %}
            <div class="{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %} 
    {% endif %}
{% endblock %}

project/templates/index.html
{% extends 'layouts/base.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}
<div class="text-center">
    <h1>Bienvenido a Mi Aplicación</h1>
    <p>Explora nuestra colección de libros y autores.</p>
</div>
{% endblock %}

project/templates/layouts/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mi Página Web{% endblock %}</title>

    <script src="https://cdn.tailwindcss.com"></script>

    <style>
        * {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
    </style>
</head>

<body class="min-h-screen flex flex-col">
    <header class="bg-fuchsia-600 text-white py-4 px-10 flex justify-between items-center rounded-b-[20px]">
        <nav class="flex space-x-5 font-bold">
            <a href="{% url 'index' %}" class="hover:underline">Inicio</a>
            <a href="{% url 'lista_autores' %}" class="hover:underline">Autores</a>
            <a href="{% url 'lista_libros' %}" class="hover:underline">Libros</a>
        </nav>

        <h1 class="text-4xl font-bold text-center flex-1">Gestión de Libros</h1>

        <div class="flex items-center space-x-4">
            {% if user.is_authenticated %}
                <span class="font-semibold">Bienvenido, {{ user.username }}!</span>
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="hover:underline">Cerrar sesión</button>
                </form>
            {% else %}
                <a href="{% url 'login' %}" class="hover:underline">Iniciar sesión</a>
                <a href="{% url 'signup' %}" class="hover:underline">Registrarse</a>
            {% endif %}
        </div>
    </header>

    <main class="flex-1">
        <div class="max-w-4xl mx-auto mt-8 p-6 bg-white rounded-lg shadow-md">
            {% block content %}
            {% endblock %}
        </div>
        <div>
            {% block actions %}
            {% endblock %}
        </div>
    </main>

    <footer class="bg-fuchsia-600 text-white text-center py-4 mt-10">
        © 2025 Gestión de Libros - Todos los derechos reservados.
    </footer>
</body>

</html>

project/templates/lista_autores.html
{% extends 'layouts/base.html' %}

{% block title %}Autores{% endblock %}

{% block content %}
    <h3 class="text-2xl font-bold mb-4">Autores:</h3>
    <ul class="list-disc pl-6">
        {% for autor in object_list %}
        <li class="text-lg mb-2 capitalize">
            <a href="{% url 'detalle_autor' autor.id %}" class="text-blue-600 hover:underline">
                {{ autor.nombre }} {{ autor.apellido }}
            </a>
        </li>
        {% empty %}
        <p>No hay autores disponibles.</p>
        {% endfor %}
    </ul>
{% endblock %}
{% block actions %}
<div class="max-w-4xl mx-auto mt-8 bg-white rounded-lg flex flex-col items-center">
    <a href="{% url 'add_autor' %}" class="bg-green-600 p-3 text-white rounded-[10px] hover:bg-green-500">Añadir Autor</a>
</div>

{% endblock %}

project/templates/lista_libros.html
{% extends 'layouts/base.html' %}

{% block title %}Libros{% endblock %}

{% block content %}
<h2 class="text-2xl font-bold mb-4">Lista de Libros:</h2>
<ul class="divide-y za divide-gray-300">
    {% for libro in object_list %}
    <li class="py-4">
        <a href="{% url 'detalle_libro' libro.id %}" class="text-lg font-semibold text-blue-600 hover:underline capitalize">
            {{ libro.titulo }}
        </a>
        <p class="text-gray-600 capitalize">Autor: {{ libro.autor.nombre }} {{ libro.autor.apellido }}</p>
    </li>
    {% empty %}
    <p class="text-gray-600">No hay libros disponibles en este momento.</p>
    {% endfor %}
</ul>
{% endblock %}
{% block actions %}
<div class="max-w-4xl mx-auto mt-8 bg-white rounded-lg flex flex-col items-center">
    <a href="{% url 'add_book' %}" class="bg-green-600 p-3 text-white rounded-[10px] hover:bg-green-500">Añadir Libro</a>
</div>
{% endblock %}